import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter, Link, NavLink, Routes, Route, useLocation, useParams } from 'react-router-dom';
import './styles.css';

const IG='https://www.instagram.com/b.i.r.d_____/';
const projects=[
 {slug:'independent-home',name:'Independent Home',location:'Kozhikode',category:'Residential',image:'home',hero:'courtyard',scope:'Planning, Design, Execution'},
 {slug:'independent-villa',name:'Independent Villa',location:'Bangalore',category:'Residential',image:'villa',hero:'villa',scope:'Planning, Interiors, Landscape'},
 {slug:'boutique-resort',name:'Boutique Resort',location:'Wayanad',category:'Hospitality',image:'resort',hero:'resort',scope:'Planning, Landscape, Project Management'},
 {slug:'interior-study',name:'Interior study',location:'Concept study',category:'Interiors',image:'interior',hero:'interior',scope:'Interior design'},
 {slug:'landscape-study',name:'Landscape study',location:'Concept study',category:'Landscape',image:'landscape',hero:'landscape',scope:'Landscape design'},
 {slug:'material-study',name:'Material study',location:'Concept study',category:'Interiors',image:'material',hero:'material',scope:'Material exploration'}
];
const services=[
 {slug:'architecture',name:'Architecture',headline:'Architecture with purpose.',description:'Contextual, climate-responsive architecture for people and place.',image:'architecture',items:['Site and context study','Concept design','Design development','Technical coordination']},
 {slug:'interiors',name:'Interiors',headline:'Spaces for everyday living.',description:'Warm, enduring interiors that elevate daily life.',image:'interior',items:['Space planning','Materials and finishes','Furniture and lighting','Execution coordination']},
 {slug:'master-planning',name:'Master planning',headline:'A larger vision for place.',description:'Holistic planning for vibrant, livable communities.',image:'landscape',items:['Site analysis','Spatial strategy','Landscape integration','Phased development']},
 {slug:'project-management',name:'Project management',headline:'Clarity at every stage.',description:'Integrated delivery for quality, clarity and impact.',image:'model',items:['Project planning','Team coordination','Progress tracking','Quality review']},
 {slug:'investment-consulting',name:'Investment consulting',headline:'Ideas with lasting value.',description:'Strategic guidance for long-term value and positive impact.',image:'resort',items:['Opportunity review','Development strategy','Feasibility coordination','Portfolio planning']}
];
function Img({name,alt,className='',eager=false}){return <img className={className} src={`./images/${name}.webp`} alt={alt} loading={eager?'eager':'lazy'}/>}
function ArrowLink({to,children,className=''}){return <Link className={`text-link ${className}`} to={to}>{children}<span aria-hidden="true">↗</span></Link>}
function Brand(){return <Link to="/" className="brand" aria-label="B.I.R.D. home"><b>B.I.R.D.</b><span>Building Industry<br/>Research Development</span></Link>}
function Header(){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>setOpen(false),[location]);return <header className="header shell"><Brand/><button className="menu-toggle" aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?'Close −':'Menu +'}</button><nav id="main-nav" className={open?'nav open':'nav'} aria-label="Main navigation"><NavLink to="/projects">Projects</NavLink><NavLink to="/studio">Studio</NavLink><NavLink to="/expertise">Expertise</NavLink><NavLink className="button" to="/contact">Contact us ↗</NavLink></nav></header>}
function Footer(){return <footer className="footer"><div className="shell"><div className="footer-top"><h2>Let’s build something<br/>meaningful.</h2><Link className="button light" to="/contact">Book a consultation ↗</Link></div><div className="footer-bottom"><Brand/><a href="mailto:BuildingResearch@gmail.com">BuildingResearch@gmail.com</a><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></div></div></footer>}
function PageIntro({eyebrow,title,subtitle,side}){return <section className="page-intro shell"><p className="eyebrow">{eyebrow}</p><div className="intro-row"><div><h1>{title}</h1>{subtitle&&<p className="subtitle">{subtitle}</p>}</div>{side&&<div className="intro-side">{side}</div>}</div></section>}
function Card({project}){return <Link className="project-card" to={`/projects/${project.slug}`}><div className="image-wrap"><Img name={project.image} alt={`${project.name} architectural concept`}/><span className="card-arrow" aria-hidden="true">↗</span></div><div className="card-title"><h3>{project.name}</h3><span className="eyebrow">{project.category}</span></div><p className="eyebrow muted">{project.location}</p></Link>}
function SectionHeading({children,to,label}){return <div className="section-heading"><h2>{children}</h2><span className="rule"/>{to&&<ArrowLink to={to}>{label}</ArrowLink>}</div>}
function Home(){return <><PageIntro eyebrow="Architecture · Interiors · Research" title={<>Finding value<br/>through design.</>} side={<><p>Thoughtful spaces. Lasting value.</p><ArrowLink to="/projects">Explore our work</ArrowLink></>}/><figure className="hero shell"><Img name="hero" alt="Illustrative tropical courtyard residence" eager/><figcaption>Spaces shaped by context <span>Concept imagery</span></figcaption></figure><section className="section shell"><SectionHeading to="/projects" label="View all projects">Selected work</SectionHeading><div className="project-grid">{projects.slice(0,2).map(p=><Card key={p.slug} project={p}/>)}</div></section><section className="green-band"><div className="shell two-col"><div><p className="eyebrow">Our studio</p><h2 className="display">Research-led.<br/>People-centred.</h2></div><div className="band-copy"><p>We bring architecture, interiors and research together to create spaces with purpose.</p><ArrowLink to="/studio">Discover the studio</ArrowLink></div></div></section><section className="section shell two-col expertise-preview"><div><p className="eyebrow">Our expertise</p><h2>From first idea<br/>to built reality.</h2><Img name="architecture" alt="Illustrative architecture surrounded by greenery"/></div><div>{services.map((s,i)=><Link className="service-mini" key={s.slug} to={`/expertise/${s.slug}`}><span>0{i+1}</span><h3>{s.name}</h3><span>↗</span></Link>)}</div></section></>}
function Projects(){const [filter,setFilter]=useState('All projects');return <><PageIntro eyebrow="Our portfolio" title="Selected work." subtitle="Architecture shaped by people and place." side={<p className="small muted">Concept imagery</p>}/><section className="shell section no-top"><div className="filters" aria-label="Project categories">{['All projects','Residential','Hospitality','Interiors','Landscape'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==='All projects'||p.category===filter).map(p=><Card key={p.slug} project={p}/>)}</div></section></>}
function ProjectDetail(){const {slug}=useParams();const p=projects.find(p=>p.slug===slug);if(!p)return <NotFound/>;const next=projects[(projects.indexOf(p)+1)%projects.length];return <><PageIntro eyebrow={<><Link to="/projects">Projects</Link> / {p.name}</>} title={p.name} side={<><p>{p.location}</p><p className="small muted">Concept imagery</p></>}/><section className="shell"><Img className="detail-hero" name={p.hero} alt={`${p.name} concept`} eager/><div className="facts">{[['Location',p.location],['Scope',p.scope],['Type',p.category]].map(([label,value])=><div key={label}><p className="eyebrow">{label}</p><p>{value}</p></div>)}</div></section><section className="section shell"><div className="two-col story"><div><h2>A space connected<br/>to its context.</h2><p>A calm retreat envisioned around light, greenery and everyday life. Open spaces invite a sense of connection, while natural materials bring warmth and character.</p><p className="small muted">Illustrative project narrative. Project photography and verified details to be supplied before publication.</p></div><Img name={p.image} alt="Architectural concept detail"/></div><div className="two-col gallery"><Img name={p.category==='Interiors'?'material':'living'} alt="Illustrative warm living space"/><Img name={p.category==='Hospitality'?'landscape':'courtyard'} alt="Illustrative courtyard detail"/></div><div className="next-project"><div><p className="eyebrow">Next project</p><ArrowLink to={`/projects/${next.slug}`}>{next.name}</ArrowLink></div><Img name={next.image} alt={next.name}/></div></section></>}
const process=[['Context','We begin with an understanding of place, people and the larger ecosystem.'],['Research','We study, question and explore to uncover opportunities.'],['Design','We translate insights into clear, thoughtful spaces.'],['Delivery','We work closely through execution to maintain intent and quality.']];
function Process({title='A connected process.',steps=process}){return <section className="green-band"><div className="shell"><p className="eyebrow">Our approach</p><h2>{title}</h2><div className="process-grid">{steps.map(([name,copy],i)=><div key={name}><p className="eyebrow">0{i+1}</p><h3>{name}</h3><p>{copy}</p></div>)}</div></div></section>}
function Studio(){const team=[['R','Ranjith','Managing Director'],['G','Gopinath','Design Lead, Infra'],['A','Amrutha','Design Lead, Retail'],['H','Hariprasad','Projects In Charge']];return <><PageIntro eyebrow="Studio / Team" title={<>Research-led.<br/>People-centred.</>} subtitle="Building Industry Research Development"/><figure className="shell hero"><Img name="studio" alt="Illustrative architecture studio with models and materials" eager/><figcaption>Studio concept imagery</figcaption></figure><section className="section shell two-col"><div><p className="eyebrow">Our philosophy</p><h2 className="display">Design,<br/>established<br/>on value.</h2></div><div className="prose"><h3>Architecture for a wider tomorrow.</h3><p>We envision contextual, lasting spaces shaped by people, place and purpose. Our approach brings architecture, interiors and research together.</p><h3>Research as a design tool.</h3><p>Curiosity about local conditions, materials and ways of living helps guide thoughtful design decisions.</p></div></section><Process title="Our approach."/><section className="section shell"><SectionHeading>Meet our team</SectionHeading><div className="team-grid">{team.map(([initial,name,role])=><article className="team-card" key={name}><div className="initial">{initial}.</div><h3>{name}</h3><p>{role}</p></article>)}</div></section><div className="shell"><Img className="texture-banner" name="material" alt="Warm timber and stone material concept"/></div></>}
function Expertise(){return <><section className="shell expertise-hero two-col"><div><p className="eyebrow">Expertise</p><h1>From first idea<br/>to built reality.</h1><p>Architecture, interiors and strategic advisory for a thoughtful tomorrow.</p></div><Img name="model" alt="Architecture model and material board concept" eager/></section><section className="shell services">{services.map((s,i)=><article className="service-row" key={s.slug}><div className="service-number">0{i+1}</div><div><h2>{s.name}</h2><p>{s.description}</p><ArrowLink to={`/expertise/${s.slug}`}>Explore</ArrowLink></div><Link to={`/expertise/${s.slug}`} aria-label={`Explore ${s.name}`}><Img name={s.image} alt={`${s.name} illustrative study`}/></Link></article>)}</section><Process/></>}
function ServiceDetail(){const {slug}=useParams();const s=services.find(s=>s.slug===slug);if(!s)return <NotFound/>;return <><PageIntro eyebrow={<><Link to="/expertise">Expertise</Link> / {s.name}</>} title={s.headline} subtitle="Spaces shaped by context, people and possibility."/><figure className="hero shell"><Img name={s.image} alt={`${s.name} concept`} eager/><figcaption>Concept imagery</figcaption></figure><section className="section shell"><div className="two-col story"><h2>Built around<br/>your vision.</h2><p>{s.description} We bring research, contextual understanding and a collaborative process to each conversation.</p></div><h2 className="bring-heading">What we bring.</h2>{s.items.map((item,i)=><div className="deliverable" key={item}><span>0{i+1}</span><h3>{item}</h3></div>)}</section><Process title="From conversation to construction." steps={['Discover','Develop','Detail','Deliver'].map((name,i)=>[name,process[i][1]])}/><section className="section shell"><SectionHeading to="/projects" label="View all projects">Selected project</SectionHeading><div className="two-col"><Img name="home" alt="Independent Home concept"/><div className="band-copy"><h2>Independent Home<br/>Kozhikode</h2><ArrowLink to="/projects/independent-home">View project</ArrowLink></div></div></section></>}
function Contact(){const [ready,setReady]=useState(false);function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const body=`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nPhone: ${f.get('phone')||'Not provided'}\nService: ${f.get('service')}\nLocation: ${f.get('location')}\n\n${f.get('message')}`;window.location.href=`mailto:BuildingResearch@gmail.com?subject=${encodeURIComponent('Website project enquiry — '+f.get('service'))}&body=${encodeURIComponent(body)}`;setReady(true)}return <><PageIntro eyebrow="Contact" title={<>Let’s start<br/>a conversation.</>} subtitle="Tell us what you have in mind."/><section className="section shell no-top contact-grid"><form onSubmit={submit}><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Phone (optional)<input name="phone" type="tel" autoComplete="tel" placeholder="Your phone number"/></label><label>Project type<select name="service" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}</select></label><label>Project location<input required name="location" placeholder="City, State"/></label><label>Tell us about your project<textarea required name="message" rows="6" placeholder="Share your goals, site context or requirements."/></label><button className="submit" type="submit">Prepare enquiry email ↗</button><p className="small muted">Opens your email app with a draft. Review and send it there.</p>{ready&&<p role="status">Your email draft is ready. If your email app did not open, contact us at BuildingResearch@gmail.com.</p>}</form><aside className="contact-info"><p className="eyebrow">Contact information</p><div><span>Email</span><a href="mailto:BuildingResearch@gmail.com">BuildingResearch@gmail.com</a></div><div><span>Phone</span><a href="tel:+919739468484">+91 97394 68484</a></div><div><span>Social</span><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></div><Img name="contact" alt="Concept detail of stone and timber architecture"/><p className="small muted">Concept imagery</p></aside></section><section className="green-band"><div className="shell"><h2>It can be a renovation, a new home,<br/>or something uniquely yours.</h2></div></section></>}
function NotFound(){return <section className="section shell"><p className="eyebrow">404</p><h1>Page not found.</h1><ArrowLink to="/">Back to home</ArrowLink></section>}
function ScrollAndTitle(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});const name=pathname.split('/').filter(Boolean).pop()?.replaceAll('-',' ')||'Architecture & Research';document.title=`${name.charAt(0).toUpperCase()+name.slice(1)} — B.I.R.D.`},[pathname]);return null}
function App(){return <HashRouter><ScrollAndTitle/><a className="skip-link" href="#content">Skip to content</a><Header/><main id="content"><Routes><Route path="/" element={<Home/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:slug" element={<ProjectDetail/>}/><Route path="/studio" element={<Studio/>}/><Route path="/expertise" element={<Expertise/>}/><Route path="/expertise/:slug" element={<ServiceDetail/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></HashRouter>}
createRoot(document.getElementById('root')).render(<App/>);
