import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter, Link, NavLink, Routes, Route, useLocation, useParams } from 'react-router-dom';
import './styles.css';

const IG='https://www.instagram.com/b.i.r.d_____/';
const projects=[
 {slug:'independent-home',name:'Independent Home',location:'Kozhikode',category:'Residential',image:'home',hero:'courtyard',scope:'Planning, Design, Execution'},
 {slug:'independent-villa',name:'Independent Villa',location:'Bangalore',category:'Residential',image:'villa',hero:'villa',scope:'Planning, Interiors, Landscape'},
 {slug:'boutique-resort',name:'Boutique Resort',location:'Wayanad',category:'Hospitality',image:'resort',hero:'resort',scope:'Planning, Landscape, Project Management'},
 {slug:'interior-study',name:'Interior study',location:'Concept study',category:'Interiors',image:'interior',hero:'interior',scope:'Interior design'},
 {slug:'landscape-study',name:'Landscape study',location:'Concept study',category:'Landscape',image:'landscape',hero:'landscape',scope:'Landscape design'},
 {slug:'material-study',name:'Material study',location:'Concept study',category:'Interiors',image:'material',hero:'material',scope:'Material exploration'}
];
const services=[
 {slug:'architecture',name:'Architecture',headline:'Architecture with purpose.',description:'Contextual, climate-responsive architecture for people and place.',image:'architecture',items:['Site and context study','Concept design','Design development','Technical coordination']},
 {slug:'interiors',name:'Interiors',headline:'Spaces for everyday living.',description:'Warm, enduring interiors that elevate daily life.',image:'interior',items:['Space planning','Materials and finishes','Furniture and lighting','Execution coordination']},
 {slug:'master-planning',name:'Master planning',headline:'A larger vision for place.',description:'Holistic planning for vibrant, livable communities.',image:'landscape',items:['Site analysis','Spatial strategy','Landscape integration','Phased development']},
 {slug:'project-management',name:'Project management',headline:'Clarity at every stage.',description:'Integrated delivery for quality, clarity and impact.',image:'model',items:['Project planning','Team coordination','Progress tracking','Quality review']},
 {slug:'investment-consulting',name:'Investment consulting',headline:'Ideas with lasting value.',description:'Strategic guidance for long-term value and positive impact.',image:'resort',items:['Opportunity review','Development strategy','Feasibility coordination','Portfolio planning']}
];
function Img({name,alt,className='',eager=false}){return <img className={className} src={`./images/${name}.webp`} alt={alt} loading={eager?'eager':'lazy'}/>}
function ArrowLink({to,children,className=''}){return <Link className={`text-link ${className}`} to={to}>{children}<span aria-hidden="true">↗</span></Link>}
function Brand(){return <Link to="/" className="brand" aria-label="B.I.R.D. home"><b>B.I.R.D.</b><span>Building Industry<br/>Research Development</span></Link>}
function Header(){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>setOpen(false),[location]);return <header className={`header shell ${location.pathname==='/'?'header-home':''}`}><Brand/><button className="menu-toggle" aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?'Close −':'Menu +'}</button><nav id="main-nav" className={open?'nav open':'nav'} aria-label="Main navigation"><NavLink to="/projects">Projects</NavLink><NavLink to="/studio">Studio</NavLink><NavLink to="/expertise">Expertise</NavLink><NavLink className={location.pathname==='/'?'button':''} to="/contact">Contact us ↗</NavLink></nav></header>}
function Footer(){const {pathname}=useLocation();const mode=pathname==='/'?'home':pathname==='/contact'?'contact':pathname==='/expertise'?'expertise':pathname==='/studio'?'studio':pathname.startsWith('/expertise/')?'service':'standard';const email=<a href="mailto:BuildingResearch@gmail.com">BuildingResearch@gmail.com</a>;const social=<a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a>;const button=<Link className="button light" to="/contact">Book a consultation ↗</Link>;return <footer className={`footer footer-${mode}`}><div className="shell">{mode==='contact'?<><h2>It can be a renovation, a new home,<br/>or something uniquely yours.</h2><div className="footer-bottom"><Brand/><Link to="/contact">Book a consultation ↗</Link>{email}{social}</div></>:mode==='home'?<div className="home-footer-grid"><h2>Let’s build something<br/>meaningful.</h2><div>{button}<div className="footer-links">{email}{social}</div></div><Brand/></div>:['studio','service'].includes(mode)?<div className="compact-footer"><h2>Let’s build something{mode==='studio'?<br/>:' '}meaningful.</h2><div>{button}<div className="footer-links">{email}{social}</div></div></div>:<><div className="footer-top"><h2>Let’s build something<br/>meaningful.</h2>{button}</div><div className="footer-bottom">{mode==='expertise'&&<Brand/>}{email}{social}</div></>}</div></footer>}
function PageIntro({eyebrow,title,subtitle,side}){return <section className="page-intro shell"><p className="eyebrow">{eyebrow}</p><div className="intro-row"><div><h1>{title}</h1>{subtitle&&<p className="subtitle">{subtitle}</p>}</div>{side&&<div className="intro-side">{side}</div>}</div></section>}
function Card({project}){return <Link className="project-card" to={`/projects/${project.slug}`}><div className="image-wrap"><Img name={project.image} alt={`${project.name} architectural concept`}/><span className="card-arrow" aria-hidden="true">↗</span></div><div className="card-title"><h3>{project.name}</h3><span className="eyebrow">{project.category}</span></div><p className="eyebrow muted">{project.location}</p></Link>}
function SectionHeading({children,to,label}){return <div className="section-heading"><h2>{children}</h2><span className="rule"/>{to&&<ArrowLink to={to}>{label}</ArrowLink>}</div>}
function Home(){return <><PageIntro eyebrow="Architecture · Interiors · Research" title={<>Finding value<br/>through design.</>} side={<><p>Thoughtful spaces. Lasting value.</p><ArrowLink to="/projects">Explore our work</ArrowLink></>}/><figure className="hero shell hero-wide"><Img name="hero" alt="Illustrative tropical courtyard residence" eager/><figcaption>Spaces shaped by context</figcaption></figure><section className="section shell home-work"><SectionHeading to="/projects" label="View all projects">Selected work</SectionHeading><div className="project-grid home-project-grid">{projects.slice(0,2).map((p,i)=><Card key={p.slug} project={{...p,image:i?'villa-selected':'home-selected'}}/>)}</div></section><section className="green-band home-studio"><div className="shell"><div className="section-label"><p className="eyebrow">Our studio</p><span/></div><div className="two-col"><h2 className="display">Research-led.<br/>People-centred.</h2><div className="band-copy"><p>We bring architecture, interiors and research together to create spaces with purpose.</p><ArrowLink to="/studio">Discover the studio</ArrowLink></div></div></div></section><section className="section shell two-col expertise-preview"><div><div className="section-label"><p className="eyebrow">Our expertise</p><span/></div><h2>From first idea<br/>to built reality.</h2><Img name="home-expertise" alt="Illustrative architecture surrounded by greenery"/></div><div>{services.map((s,i)=><Link className="service-mini" key={s.slug} to={`/expertise/${s.slug}`}><span>0{i+1}</span><h3>{s.name}</h3><span>→</span></Link>)}</div></section></>}
function Projects(){const [filter,setFilter]=useState('All projects');return <><PageIntro title="Selected work." subtitle="Architecture shaped by people and place." side={<p className="small muted">Concept imagery</p>}/><section className="shell section no-top"><div className="filters" aria-label="Project categories">{['All projects','Residential','Hospitality','Interiors','Landscape'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==='All projects'||p.category===filter).map(p=><Card key={p.slug} project={p}/>)}</div></section></>}
function ProjectDetail(){const {slug}=useParams();const p=projects.find(p=>p.slug===slug);if(!p)return <NotFound/>;const home=p.slug==='independent-home';const next=projects[(projects.indexOf(p)+1)%projects.length];return <><PageIntro eyebrow={<><Link to="/projects">Projects</Link> / {p.name}</>} title={home?<>Independent<br/>Home</>:p.name} side={<><p>{p.location}</p><p className="small muted">Concept imagery</p></>}/><section className="shell"><Img className="detail-hero" name={p.hero} alt={`${p.name} concept`} eager/><div className="facts">{[['Location',p.location],['Scope',p.scope],['Type',p.category]].map(([label,value])=><div key={label}><p className="eyebrow">{label}</p><p>{value}</p></div>)}</div></section><section className="section shell project-story"><div className="two-col story"><div><h2>{home?<>A home connected<br/>to nature.</>:<>A space connected<br/>to its context.</>}</h2><p>An independent {p.category==='Residential'?'home':'space'} envisioned as a calm retreat, rooted in its context. Open spaces, natural light and greenery flow through the design, creating a sense of openness and belonging. Generous gathering spaces encourage togetherness, while natural materials bring warmth and timelessness to everyday living.</p><p className="small muted">Illustrative project narrative</p></div><Img name={home?'project-side':p.image} alt="Architectural concept detail"/></div><div className="two-col gallery"><Img name={p.category==='Interiors'?'material':'living'} alt="Illustrative warm living space"/><Img name={home?'project-detail':p.category==='Hospitality'?'landscape':'courtyard'} alt="Illustrative courtyard detail"/></div><div className="next-project"><div><p className="eyebrow">Next project</p><ArrowLink to={`/projects/${next.slug}`}>{next.name}</ArrowLink></div><Img name={home?'project-next':next.image} alt={next.name}/></div></section></>}
const process=[['Context','We begin with an understanding of place, people and the larger ecosystem.'],['Research','We study, question and explore to uncover opportunities.'],['Design','We translate insights into clear, thoughtful spaces.'],['Delivery','We work closely through execution to maintain intent and quality.']];
function Process({title='A connected process.',steps=process,compact=false,lead}){return <section className={`green-band process-band ${compact?'process-compact':''}`}><div className="shell">{compact?<p className="eyebrow">Our approach</p>:<><p className="eyebrow">Our approach</p><div className="process-intro"><h2>{title}</h2>{lead&&<p>{lead}</p>}</div></>}<div className="process-grid">{steps.map(([name,copy],i)=><div key={name}><p className="process-number">0{i+1}</p><h3>{name}</h3><p>{copy}</p></div>)}</div></div></section>}
function Studio(){const team=[['R','Ranjith','Managing Director','Guides the studio’s vision, partnerships and long-term growth, with a focus on responsible and impactful built environments.'],['G','Gopinath','Design Lead, Infra','Leads infrastructure and large-scale projects with a strong focus on context, systems thinking and sustainable outcomes.'],['A','Amrutha','Design Lead, Retail','Heads retail design with a focus on people, place and brand experience, creating distinctive and enduring spaces.'],['H','Hariprasad','Projects In Charge','Oversees project coordination and delivery, ensuring design intent is realized with quality, clarity and efficiency.']];return <><PageIntro eyebrow="Studio / Team" title={<>Research-led.<br/>People-centred.</>} subtitle="Building Industry Research Development" side={<p>We are an architecture studio shaped by research, grounded in context and driven by people.</p>}/><figure className="shell hero studio-hero"><Img name="studio" alt="Illustrative architecture studio with models and materials" eager/><figcaption>Studio concept imagery</figcaption></figure><section className="section shell two-col studio-philosophy"><div><p className="eyebrow">Our philosophy</p><h2 className="display">Design,<br/>established<br/>on value.</h2></div><div className="prose"><h3>Architecture for a wider tomorrow.</h3><p>We design spaces that are contextual, lasting and meaningful — shaped by people, place and purpose. Our work balances aesthetics, functionality and responsibility to create built environments that enrich everyday life.</p><span className="short-rule"/><h3>Research as a design tool.</h3><p>We use research to inform better decisions — from understanding local conditions and materials to exploring new typologies and sustainable practices. Research keeps our design process curious, rigorous and relevant.</p></div></section><Process compact/><section className="section shell team-section"><div className="team-heading"><p className="eyebrow">Meet our team</p><p>A multidisciplinary team united by a shared belief<br/>in thoughtful, responsible and people-centred design.</p></div><div className="team-grid">{team.map(([,name,role,copy])=><article className="team-card" key={name}><img className={`team-portrait team-portrait-${name.toLowerCase()}`} src={`./images/team-${name.toLowerCase()}.jpg`} alt={`${name}, ${role}`} loading="lazy" width="640" height="640"/><h3>{name}</h3><p className="team-role">{role}</p><span className="short-rule"/><p className="team-description">{copy}</p></article>)}</div></section><Img className="texture-banner" name="studio-texture" alt="Warm timber and stone material concept"/></>}
function Expertise(){return <><section className="expertise-hero"><div className="shell two-col"><div><p className="eyebrow">Expertise</p><h1>From first idea<br/>to built reality.</h1><p>Architecture, interiors and strategic advisory<br/>for a thoughtful, resilient tomorrow.</p></div><Img name="model" alt="Architecture model and material board concept" eager/></div></section><section className="services">{services.map((s,i)=><article className="service-row-wrap" key={s.slug}><div className="shell service-row"><div className="service-number">0{i+1}</div><div className="service-copy"><h2>{s.name}</h2><p>{s.description}</p><ArrowLink to={`/expertise/${s.slug}`}>Explore</ArrowLink></div><Link className="service-photo-pair" to={`/expertise/${s.slug}`} aria-label={`Explore ${s.name}`}><Img name={'service-'+s.slug} alt={`${s.name} illustrative study`}/><Img name={'service-'+s.slug+'-detail'} alt={`${s.name} material detail`}/></Link></div></article>)}</section><Process lead="Ideas, expertise and execution working together — from initial conversations to spaces that endure." steps={[['Listen','Understand people, place and possibility.'],['Research','Uncover insights through context, data and dialogue.'],['Design','Thoughtful, responsible solutions.'],['Deliver','Bring ideas to life with care and precision.']]}/></>}
function ServiceDetail(){const {slug}=useParams();const s=services.find(s=>s.slug===slug);if(!s)return <NotFound/>;const descriptions=['Understanding the land, climate, culture and opportunities that shape the project.','Exploring ideas, spatial strategies and informed directions for your vision.','Refining the design through materials, systems and detailed resolution.','Working with consultants and contractors to translate design into buildable, high-quality outcomes.'];return <><PageIntro eyebrow={<><Link to="/expertise">Expertise</Link> / {s.name}</>} title={s.slug==='architecture'?<>Architecture<br/>with purpose.</>:s.headline} subtitle="Spaces shaped by context, people and possibility."/><figure className="hero shell service-detail-hero"><Img name={s.image} alt={`${s.name} concept`} eager/><figcaption>Concept imagery</figcaption></figure><section className="section shell service-detail-content"><div className="two-col story"><h2>Built around<br/>your vision.</h2><p>We design spaces that grow from place, people and purpose. Our practice brings together rigorous research, contextual understanding and a collaborative process to create meaningful, enduring environments — from homes to workplaces and cultural spaces.</p></div><h2 className="bring-heading">What we bring.</h2>{s.items.map((item,i)=><div className="deliverable" key={item}><span>0{i+1}</span><h3>{item}</h3><p>{descriptions[i]}</p></div>)}</section><Process title={<>From conversation<br/>to construction.</>} steps={[['Discover','Listening to your needs and understanding context.'],['Develop','Shaping ideas into clear design propositions.'],['Detail','Resolving design, materials and technical information.'],['Deliver','Supporting the build towards a lasting, meaningful space.']]}/><section className="section shell selected-service-project"><p className="eyebrow">Selected project</p><div className="two-col"><Img name="service-selected" alt="Independent Home concept"/><div className="band-copy"><h3>Independent Home /<br/>Kozhikode</h3><ArrowLink to="/projects/independent-home">View project</ArrowLink></div></div></section></>}
function Contact(){const [ready,setReady]=useState(false);function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);const body=`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nPhone: ${f.get('phone')||'Not provided'}\nService: ${f.get('service')}\nLocation: ${f.get('location')}\n\n${f.get('message')}`;window.location.href=`mailto:BuildingResearch@gmail.com?subject=${encodeURIComponent('Website project enquiry — '+f.get('service'))}&body=${encodeURIComponent(body)}`;setReady(true)}return <><PageIntro title={<>Let’s start<br/>a conversation.</>} subtitle="Tell us what you have in mind."/><section className="section shell no-top contact-grid"><form onSubmit={submit}><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Phone (optional)<input name="phone" type="tel" autoComplete="tel" placeholder="Your phone number"/></label><label>Project type<select name="service" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}</select></label><label>Project location<input required name="location" placeholder="City, State"/></label><label>Tell us about your project<textarea required name="message" rows="6" placeholder="Share your goals, site context or requirements."/></label><button className="submit" type="submit">Prepare enquiry email ↗</button><p className="small muted">Opens your email app with a draft. Review and send it there.</p>{ready&&<p role="status">Your email draft is ready. If your email app did not open, contact us at BuildingResearch@gmail.com.</p>}</form><aside className="contact-info"><p className="eyebrow">Contact information</p><div><span>Email</span><a href="mailto:BuildingResearch@gmail.com">BuildingResearch@gmail.com</a></div><div><span>Phone</span><a href="tel:+919739468484">+91 97394 68484</a></div><div><span>Social</span><a href={IG} target="_blank" rel="noreferrer">Instagram ↗</a></div><Img name="contact" alt="Concept detail of stone and timber architecture"/><p className="small muted">Concept imagery</p></aside></section></>}
function NotFound(){return <section className="section shell"><p className="eyebrow">404</p><h1>Page not found.</h1><ArrowLink to="/">Back to home</ArrowLink></section>}
function ScrollAndTitle(){const {pathname}=useLocation();useEffect(()=>{document.body.dataset.page=pathname==='/'?'home':pathname.startsWith('/projects/')?'project-detail':pathname.startsWith('/expertise/')?'service-detail':pathname.slice(1);window.scrollTo({top:0,behavior:'instant'});const name=pathname.split('/').filter(Boolean).pop()?.replaceAll('-',' ')||'Architecture & Research';document.title=`${name.charAt(0).toUpperCase()+name.slice(1)} — B.I.R.D.`},[pathname]);return null}
function App(){return <HashRouter><ScrollAndTitle/><a className="skip-link" href="#content">Skip to content</a><Header/><main id="content" className="page-content"><Routes><Route path="/" element={<Home/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:slug" element={<ProjectDetail/>}/><Route path="/studio" element={<Studio/>}/><Route path="/expertise" element={<Expertise/>}/><Route path="/expertise/:slug" element={<ServiceDetail/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></HashRouter>}
createRoot(document.getElementById('root')).render(<App/>);
